// Kling Video Effects — 263 個特效模板。
// 來源：官方 Excel 報價表 (Video Effect_2026-05-04.xlsx)
// 每筆：scene (API key), zh (中文), units (API resource-pack 扣款), category
// 1 unit ≈ $0.14 USD

export const EFFECT_CATEGORIES = [
  { id: 'all',         label: '全部' },
  { id: 'cny',         label: '春節 / 節慶' },
  { id: 'christmas',   label: '聖誕' },
  { id: 'halloween',   label: '萬聖節' },
  { id: 'dance',       label: '舞蹈' },
  { id: 'transform',   label: '變身' },
  { id: 'wings',       label: '翅膀' },
  { id: 'pet',         label: '寵物' },
  { id: 'action',      label: '動作' },
  { id: 'romance',     label: '浪漫 / 親密' },
  { id: 'visual',      label: '視覺特效' },
  { id: 'transition',  label: '轉場' },
  { id: 'birthday',    label: '生日' },
  { id: 'character',   label: '人物 / 角色' },
  { id: 'effect',      label: '一般特效' },
]

// Effects organized by approximate theme. Some categorizations are subjective.
export const KLING_EFFECTS = [
  // === 動作 / 視覺 ===
  { scene: 'raid_check',                 zh: '突擊檢查',          en: 'Raid Check',                 units: 4.5, category: 'action' },
  { scene: 'color_mixing',               zh: '色彩混合',          en: 'Color Mixing',               units: 4,   category: 'visual' },
  { scene: 'toss_run',                   zh: '拋擲奔跑',          en: 'Toss & Run',                 units: 6,   category: 'action' },
  { scene: 'palm_sized_figure_pro',      zh: '掌上人偶 Pro',      en: 'Palm Sized Figure Pro',      units: 3,   category: 'visual' },
  { scene: 'tiny_beast_printer',         zh: '迷你獸印表機',      en: 'Tiny Beast Printer',         units: 4.5, category: 'visual' },
  { scene: 'landmark_reveal',            zh: '地標揭幕',          en: 'Landmark Reveal',            units: 4,   category: 'visual' },
  { scene: 'winter_charm',               zh: '冬日魅力',          en: 'Winter Charm',               units: 1.7, category: 'visual' },
  { scene: 'flash_ride',                 zh: '閃電飛馳',          en: 'Flash Ride',                 units: 2.7, category: 'action' },
  { scene: 'maestro_of_magic',           zh: '魔法大師',          en: 'Maestro Of Magic',           units: 1.7, category: 'character' },
  { scene: 'magic_carpet_ride',          zh: '魔毯飛行',          en: 'Magic Carpet Ride',          units: 2.7, category: 'action' },
  { scene: 'good_luck_spirit',           zh: '幸運精靈',          en: 'Good Luck Spirit',           units: 2.7, category: 'character' },
  { scene: 'shooting_star',              zh: '流星許願',          en: 'Shooting Star',              units: 2,   category: 'visual' },
  { scene: 'sparkler_wand',              zh: '仙女棒',            en: 'Sparkler Wand',              units: 1.7, category: 'visual' },
  { scene: 'sovereign_scepter',          zh: '王者權杖',          en: 'Sovereign Scepter',          units: 4,   category: 'character' },
  { scene: 'dirt_rush',                  zh: '塵土飛揚',          en: 'Dirt Rush',                  units: 2.7, category: 'action' },
  { scene: 'return_of_the_king',         zh: '王者歸來',          en: 'Return Of The King',         units: 2.7, category: 'character' },
  { scene: 'dance_with_dragon',          zh: '與龍共舞',          en: 'Dance With Dragon',          units: 2.7, category: 'cny' },
  { scene: 'minimalist_light',           zh: '極簡光影',          en: 'Minimalist Light',           units: 4,   category: 'visual' },
  { scene: 'martial_meow',               zh: '武術小貓',          en: 'Martial Meow',               units: 8,   category: 'pet' },
  { scene: 'sassy_shake',                zh: '俏皮搖擺',          en: 'Sassy Shake',                units: 5,   category: 'dance' },
  { scene: 'knock_at_a_door_revenge',    zh: '敲門復仇',          en: 'Knock At A Door Revenge',    units: 6,   category: 'action' },
  { scene: 'perler_beads',               zh: '拼豆豆',            en: 'Perler Beads',               units: 4,   category: 'visual' },
  { scene: 'spring_bloom',               zh: '春暖花開',          en: 'Spring Bloom',               units: 4,   category: 'cny' },
  { scene: 'switch_to_silk',             zh: '絲綢變裝',          en: 'Switch To Silk',             units: 5.5, category: 'transform' },
  { scene: 'get_rich_quick',             zh: '一夜暴富',          en: 'Get Rich Quick',             units: 8.5, category: 'cny' },
  { scene: 'make_it_rain',               zh: '撒錢雨',            en: 'Make It Rain',               units: 3.5, category: 'cny' },
  { scene: 'twist_shake',                zh: '扭一扭',            en: 'Twist Shake',                units: 2.5, category: 'dance' },
  { scene: 'the_hip_sway',               zh: '扭胯舞',            en: 'The Hip Sway',               units: 5,   category: 'dance' },
  { scene: 'send_my_love',               zh: '送上我的愛',        en: 'Send My Love',               units: 2,   category: 'romance' },
  { scene: 'funky_martian',              zh: '放克火星人',        en: 'Funky Martian',              units: 5,   category: 'dance' },
  { scene: 'wealth_drive',               zh: '財運駕到',          en: 'Wealth Drive',               units: 3.5, category: 'cny' },
  { scene: 'the_high_kick',              zh: '高踢腿',            en: 'The High Kick',              units: 1.5, category: 'action' },
  { scene: 'the_exercise',               zh: '健身操',            en: 'The Exercise',               units: 2,   category: 'action' },
  { scene: 'lucky_veggie',               zh: '幸運蔬菜',          en: 'Lucky Veggie',               units: 5,   category: 'cny' },
  { scene: 'prank_box',                  zh: '惡作劇盒',          en: 'Prank Box',                  units: 4.5, category: 'effect' },
  { scene: 'studio_look',                zh: '攝影棚妝容',        en: 'Studio Look',                units: 8,   category: 'character' },
  { scene: 'flash_drive',                zh: '極速狂奔',          en: 'Flash Drive',                units: 8.5, category: 'action' },
  { scene: 'shush_my_dreams',            zh: '夢中靜音',          en: 'Shush My Dreams',            units: 4.5, category: 'effect' },
  { scene: 'french_elegance',            zh: '法式優雅',          en: 'French Elegance',            units: 9,   category: 'character' },
  { scene: 'finger_swipe',               zh: '手指滑動',          en: 'Finger Swipe',               units: 3,   category: 'transition' },
  { scene: 'advent_of_flora',            zh: '繁花盛開',          en: 'Advent of Flora',            units: 4,   category: 'visual' },
  { scene: 'smooth_transition',          zh: '平滑轉場',          en: 'Smooth Transition',          units: 2.5, category: 'transition' },
  { scene: 'skyfall',                    zh: '天降神兵',          en: 'Skyfall',                    units: 7.7, category: 'action' },
  { scene: 'snow_night_kiss',            zh: '雪夜之吻',          en: 'Snow Night Kiss',            units: 1.7, category: 'romance' },
  { scene: 'eternal_kiss',               zh: '永恆之吻',          en: 'Eternal Kiss',               units: 1.7, category: 'romance' },
  { scene: 'palm_sized_figure',          zh: '掌上人偶',          en: 'Palm Sized Figure',          units: 3,   category: 'visual' },
  { scene: 'tangyuan_to_animal',         zh: '湯圓變動物',        en: 'Tangyuan To Animal',         units: 2.5, category: 'cny' },
  { scene: 'lantern_festival_cuju',      zh: '元宵踢蹴鞠',        en: 'Lantern Festival Cuju',      units: 1.7, category: 'cny' },
  { scene: 'fortune_in_motion',          zh: '財運亨通',          en: 'Fortune In Motion',          units: 7,   category: 'cny' },
  { scene: 'chinese_trend',              zh: '國潮風',            en: 'Chinese Trend',              units: 7.5, category: 'cny' },
  { scene: 'sedan_chair_dance',          zh: '抬轎子舞',          en: 'Sedan Chair Dance',          units: 7,   category: 'dance' },
  { scene: 'expression_challenge',       zh: '表情挑戰',          en: 'Expression Challenge',       units: 5,   category: 'effect' },

  // === 舞蹈系 ===
  { scene: 'drunk_dance',                zh: '醉酒舞',            en: 'Drunk Dance',                units: 7,   category: 'dance' },
  { scene: 'drunk_dance_pet',            zh: '寵物醉酒舞',        en: 'Drunk Dance Pet',            units: 7,   category: 'dance' },
  { scene: 'daoma_dance',                zh: '刀馬旦舞',          en: 'Daoma Dance',                units: 5,   category: 'dance' },
  { scene: 'bouncy_dance',               zh: '彈跳舞',            en: 'Bouncy Dance',               units: 4.5, category: 'dance' },
  { scene: 'smooth_sailing_dance',       zh: '一帆風順舞',        en: 'Smooth Sailing Dance',       units: 7,   category: 'dance' },
  { scene: 'hot_feet_dance',             zh: '熱舞',              en: 'Hot Feet Dance',             units: 5,   category: 'dance' },
  { scene: 'swag_dance',                 zh: '搖擺舞',            en: 'Swag Dance',                 units: 5.5, category: 'dance' },
  { scene: 'pigeon_dance',               zh: '鴿子舞',            en: 'Pigeon Dance',               units: 5.5, category: 'dance' },
  { scene: 'bloodline_dance',            zh: '血脈覺醒舞',        en: 'Bloodline Dance',            units: 5.5, category: 'dance' },
  { scene: 'chanel_dance',               zh: '香奈兒舞',          en: 'Chanel Dance',               units: 4.5, category: 'dance' },
  { scene: 'cute_dance',                 zh: '可愛舞',            en: 'Cute Dance',                 units: 6,   category: 'dance' },
  { scene: 'love_theme_song',            zh: '愛情主題曲',        en: 'Love Theme Song',            units: 5.5, category: 'dance' },
  { scene: 'pumpitup_dance',             zh: 'Pump It Up 舞',     en: 'Pumpitup Dance',             units: 5.5, category: 'dance' },
  { scene: 'overdrive',                  zh: '超載狂飆',          en: 'OverDrive',                  units: 2.5, category: 'effect' },
  { scene: 'heart_gesture_dance',        zh: '比心舞',            en: 'Heart Gesture Dance',        units: 4,   category: 'dance' },
  { scene: 'motorcycle_dance',           zh: '機車舞',            en: 'Motorcycle Dance',           units: 4,   category: 'dance' },
  { scene: 'subject_3_dance',            zh: '科目三',            en: 'Subject 3 Dance',            units: 2.5, category: 'dance' },
  { scene: 'ghost_step_dance',           zh: '鬼步舞',            en: 'Ghost Step Dance',           units: 2,   category: 'dance' },
  { scene: 'yangge_dance',               zh: '秧歌舞',            en: 'Yangge Dance',               units: 5,   category: 'dance' },
  { scene: 'good_luck_dance',            zh: '好運舞',            en: 'Good Luck Dance',            units: 6.5, category: 'cny' },
  { scene: 'laicai_dance',               zh: '招財舞',            en: 'Laicai Dance',               units: 6.5, category: 'cny' },

  // === 春節 ===
  { scene: 'unique_firework',            zh: '專屬煙火',          en: 'Unique Firework',            units: 2.5, category: 'cny' },
  { scene: 'unique_spring_couplets',     zh: '專屬春聯',          en: 'Unique Spring Couplets',     units: 2.5, category: 'cny' },
  { scene: 'city_to_village',            zh: '城市變鄉村',        en: 'City To Village',            units: 4,   category: 'transform' },
  { scene: 'fortune_knocks_cartoon',     zh: '財神報到（卡通）',  en: 'Fortune Knocks Cartoon',     units: 1.7, category: 'cny' },
  { scene: 'fortune_god_transform',      zh: '財神變身',          en: 'Fortune God Transform',      units: 2.5, category: 'cny' },
  { scene: 'new_year_feast',             zh: '年夜飯',            en: 'New Year Feast',             units: 2.5, category: 'cny' },
  { scene: 'ring_in_new',                zh: '迎新年',            en: 'Ring In New',                units: 1.6, category: 'cny' },
  { scene: 'new_year_greeting',          zh: '新年祝福',          en: 'New Year Greeting',          units: 1.6, category: 'cny' },
  { scene: 'lion_dance',                 zh: '舞獅',              en: 'Lion Dance',                 units: 1.6, category: 'cny' },
  { scene: 'prosperity',                 zh: '繁榮昌盛',          en: 'Prosperity',                 units: 2.7, category: 'cny' },
  { scene: 'great_success',              zh: '大功告成',          en: 'Great Success',              units: 2.5, category: 'cny' },
  { scene: 'horse_year_firework',        zh: '馬年煙火',          en: 'Horse Year Firework',        units: 2.5, category: 'cny' },
  { scene: 'golden_horse_fortune',       zh: '金馬財運',          en: 'Golden Horse Fortune',       units: 1.6, category: 'cny' },
  { scene: 'red_packet_box',             zh: '紅包開箱',          en: 'Red Packet Unboxing',        units: 2.5, category: 'cny' },
  { scene: 'lucky_horse_year',           zh: '幸運馬年',          en: 'Lucky Horse Year',           units: 2.5, category: 'cny' },
  { scene: 'horse_mask',                 zh: '馬頭面具',          en: 'Horse Mask',                 units: 1.5, category: 'cny' },
  { scene: 'lucky_red_packet',           zh: '幸運紅包',          en: 'Lucky Red Packet',           units: 1.6, category: 'cny' },
  { scene: 'lucky_money_come',           zh: '財源滾滾',          en: 'Lucky Money Come',           units: 1.6, category: 'cny' },
  { scene: 'lantern_glow',               zh: '燈籠光芒',          en: 'Lantern Glow',               units: 2.5, category: 'cny' },
  { scene: 'crystal_horse',              zh: '水晶馬',            en: 'Crystal Horse',              units: 2.7, category: 'cny' },

  // === 寵物 ===
  { scene: 'pet_vlogger',                zh: '寵物 Vlog',         en: 'Pet Vlogger',                units: 6,   category: 'pet' },
  { scene: 'lion_dance_pet',             zh: '寵物舞獅',          en: 'Lion Dance Pet',             units: 1.6, category: 'pet' },
  { scene: 'dumpling_making_pet',        zh: '寵物包餃子',        en: 'Dumpling Making Pet',        units: 2.5, category: 'pet' },
  { scene: 'fish_making_pet',            zh: '寵物煮魚',          en: 'Fish Making Pet',            units: 2.5, category: 'pet' },
  { scene: 'pet_red_packet',             zh: '寵物紅包',          en: 'Pet Red Packet',             units: 1.6, category: 'pet' },
  { scene: 'pet_chinese_opera',          zh: '寵物京劇',          en: 'Pet Chinese Opera',          units: 1,   category: 'pet' },
  { scene: 'pet_moto_rider',             zh: '寵物機車手',        en: 'Pet Moto Rider',             units: 2,   category: 'pet' },
  { scene: 'muscle_pet',                 zh: '肌肉寵物',          en: 'Muscle Pet',                 units: 1,   category: 'pet' },
  { scene: 'pet_delivery',               zh: '寵物送外賣',        en: 'Pet Delivery',               units: 1,   category: 'pet' },
  { scene: 'pet_chef',                   zh: '寵物廚師',          en: 'Pet Chef',                   units: 1,   category: 'pet' },
  { scene: 'pet_wizard',                 zh: '寵物巫師',          en: 'Pet Wizard',                 units: 1,   category: 'pet' },
  { scene: 'pet_warrior',                zh: '寵物戰士',          en: 'Pet Warrior',                units: 1,   category: 'pet' },
  { scene: 'pet_dance',                  zh: '寵物跳舞',          en: 'Pet Dance',                  units: 1,   category: 'pet' },
  { scene: 'pet_bee',                    zh: '寵物蜜蜂',          en: 'Pet Bee',                    units: 2,   category: 'pet' },
  { scene: 'pet_bee_pro',                zh: '寵物蜜蜂 Pro',      en: 'Pet Bee Pro',                units: 1.5, category: 'pet' },
  { scene: 'pet_lion_pro',               zh: '寵物獅子 Pro',      en: 'Pet Lion Pro',               units: 1.5, category: 'pet' },
  { scene: 'tiger_hug_pro',              zh: '老虎抱抱 Pro',      en: 'Tiger Hug Pro',              units: 1.5, category: 'pet' },
  { scene: 'eagle_snatch',               zh: '老鷹叼走',          en: 'Eagle Snatch',               units: 1,   category: 'pet' },

  // === 動作 ===
  { scene: 'poping',                     zh: '機械舞',            en: 'Poping',                     units: 2,   category: 'dance' },
  { scene: 'martial_arts',               zh: '武術',              en: 'Martial Arts',               units: 4,   category: 'action' },
  { scene: 'running',                    zh: '奔跑',              en: 'Running',                    units: 3,   category: 'action' },
  { scene: 'nezha',                      zh: '哪吒',              en: 'Nezha',                      units: 4.5, category: 'character' },
  { scene: 'phantom_jewel',              zh: '幻影寶石',          en: 'Phantom Jewel',              units: 4,   category: 'visual' },

  // === 轉場 ===
  { scene: 'lateral_shift_transition',   zh: '橫向位移轉場',      en: 'Lateral Shift Transition',   units: 2.7, category: 'transition' },
  { scene: 'zoom_out',                   zh: '推遠鏡頭',          en: 'Zoom Out',                   units: 1.5, category: 'transition' },

  // === 跨年 / 新年 ===
  { scene: 'cheers_2026',                zh: '2026 乾杯',         en: 'Cheers 2026',                units: 2.5, category: 'cny' },
  { scene: 'countdown_teleport',         zh: '倒數傳送',          en: 'Countdown Teleport',         units: 3,   category: 'cny' },
  { scene: 'firework_2026',              zh: '2026 煙火',         en: 'Firework 2026',              units: 2.7, category: 'cny' },
  { scene: 'glamour_photo_shoot',        zh: '魅力寫真',          en: 'Glamour Photo Shoot',        units: 1.7, category: 'character' },
  { scene: 'box_of_joy',                 zh: '驚喜盒',            en: 'Box Of Joy',                 units: 1.7, category: 'effect' },
  { scene: 'first_toast_of_the_year',    zh: '新年第一杯',        en: 'First Toast Of The Year',    units: 3,   category: 'cny' },

  // === 聖誕 ===
  { scene: 'santa_random_surprise',      zh: '精靈頑皮咒',        en: 'Elf Playful Spell',          units: 1.5, category: 'christmas' },
  { scene: 'magic_match_tree',           zh: '魔法聖誕樹',        en: 'Magic Match Tree',           units: 2.5, category: 'christmas' },
  { scene: 'my_santa_pic',               zh: '我的聖誕照',        en: 'My Santa Pic',               units: 2.7, category: 'christmas' },
  { scene: 'santa_gift',                 zh: '聖誕禮物',          en: 'Santa Gift',                 units: 1.7, category: 'christmas' },
  { scene: 'santa_gifts',                zh: '聖誕老人送禮',      en: 'Santa Gifts',                units: 1,   category: 'christmas' },
  { scene: 'santa_hug',                  zh: '聖誕老人抱抱',      en: 'Santa Hug',                  units: 1,   category: 'christmas' },
  { scene: 'santa_express',              zh: '聖誕特快車',        en: 'Santa Express',              units: 2,   category: 'christmas' },
  { scene: 'instant_christmas',          zh: '瞬間聖誕',          en: 'Instant Christmas',          units: 3,   category: 'christmas' },
  { scene: 'particle_santa_surround',    zh: '聖誕粒子環繞',      en: 'Particle Santa Surround',    units: 2,   category: 'christmas' },
  { scene: 'jumping_ginger_joy',         zh: '薑餅人歡跳',        en: 'Jumping Ginger Joy',         units: 2.5, category: 'christmas' },
  { scene: 'coronation_of_frost',        zh: '霜之加冕',          en: 'Coronation of Frost',        units: 3,   category: 'christmas' },
  { scene: 'building_sweater',           zh: '建築變毛衣',        en: 'Building Sweater',           units: 3,   category: 'christmas' },
  { scene: 'spark_in_the_snow',          zh: '雪中火花',          en: 'Spark In The Snow',          units: 1.7, category: 'christmas' },
  { scene: 'scarlet_and_snow',           zh: '紅與雪',            en: 'Scarlet And Snow',           units: 1.7, category: 'christmas' },
  { scene: 'cozy_toon_wrap',             zh: '溫暖卡通包覆',      en: 'Cozy Toon Wrap',             units: 2.7, category: 'christmas' },
  { scene: 'snowboarding',               zh: '滑雪板',            en: 'Snowboarding',               units: 2.5, category: 'action' },
  { scene: 'steampunk_christmas',        zh: '蒸汽龐克聖誕',      en: 'Steampunk Christmas',        units: 1.7, category: 'christmas' },
  { scene: 'snowglobe',                  zh: '雪花球',            en: 'Snowglobe',                  units: 1.7, category: 'christmas' },
  { scene: 'christmas_photo_shoot',      zh: '聖誕寫真',          en: 'Christmas Photo Shoot',      units: 1.7, category: 'christmas' },
  { scene: 'ornament_crash',             zh: '掛飾砸下',          en: 'Ornament Crash',             units: 1.5, category: 'christmas' },

  // === 子彈時間 / 動作 ===
  { scene: 'bullet_time_lite',           zh: '子彈時間 Pro',      en: 'Bullet Time Pro',            units: 4,   category: 'action' },
  { scene: 'bullet_time',                zh: '子彈時間',          en: 'Bullet Time',                units: 7,   category: 'action' },
  { scene: 'bullet_time_360',            zh: '子彈時間 360',      en: 'Bullet Time 360',            units: 2.5, category: 'action' },
  { scene: 'magic_cloak',                zh: '魔法斗篷',          en: 'Magic Cloak',                units: 1.5, category: 'character' },

  // === 生日 ===
  { scene: 'happy_birthday',             zh: '蛋糕送達',          en: 'Cake Delivery',              units: 4,   category: 'birthday' },
  { scene: 'birthday_star',              zh: '生日壽星',          en: 'Birthday Star',              units: 3,   category: 'birthday' },

  // === 雙人/浪漫 Pro ===
  { scene: 'heart_gesture_pro',          zh: '比心 Pro',          en: 'Heart Gesture Pro',          units: 1.5, category: 'romance' },
  { scene: 'fight_pro',                  zh: '對決 Pro',          en: 'Fight Pro',                  units: 1.5, category: 'action' },
  { scene: 'hug_pro',                    zh: '擁抱 Pro',          en: 'Hug Pro',                    units: 1.5, category: 'romance' },
  { scene: 'kiss_pro',                   zh: '親吻 Pro',          en: 'Kiss Pro',                   units: 1.5, category: 'romance' },
  { scene: 'dollar_rain_pro',            zh: '美元雨 Pro',        en: 'Dollar Rain Pro',            units: 1.5, category: 'cny' },
  { scene: 'thumbs_up_pro',              zh: '比讚 Pro',          en: 'Thumbs Up Pro',              units: 1.5, category: 'effect' },

  // === 花束 / 浪漫 ===
  { scene: 'surprise_bouquet',           zh: '驚喜花束',          en: 'Surprise Bouquet',           units: 2.5, category: 'romance' },
  { scene: 'bouquet_drop',               zh: '花束從天降',        en: 'Bouquet Drop',                units: 2.5, category: 'romance' },

  // === 卡通風格 ===
  { scene: '3d_cartoon_1_pro',           zh: '3D 卡通 1 Pro',     en: '3D Cartoon 1 Pro',           units: 1.7, category: 'transform' },
  { scene: 'c4d_cartoon_pro',            zh: 'C4D 卡通 Pro',      en: 'C4D Cartoon Pro',            units: 1.7, category: 'transform' },
  { scene: '3d_cartoon_2',               zh: '3D 卡通 2',         en: '3D Cartoon 2',               units: 1.2, category: 'transform' },

  // === 翅膀 ===
  { scene: 'balloon_parade',             zh: '氣球遊行',          en: 'Balloon Parade',             units: 2.5, category: 'visual' },
  { scene: 'pure_white_wings',           zh: '純白翅膀',          en: 'Pure White Wings',           units: 2.5, category: 'wings' },
  { scene: 'black_wings',                zh: '黑色翅膀',          en: 'Black Wings',                units: 2.5, category: 'wings' },
  { scene: 'golden_wing',                zh: '金色翅膀',          en: 'Golden Wing',                units: 2.5, category: 'wings' },
  { scene: 'pink_pink_wings',            zh: '粉色翅膀',          en: 'Pink Wings',                 units: 2.5, category: 'wings' },
  { scene: 'fairy_wing',                 zh: '仙子翅膀',          en: 'Fairy Wing',                 units: 2,   category: 'wings' },
  { scene: 'angel_wing',                 zh: '天使翅膀',          en: 'Angel Wing',                 units: 2,   category: 'wings' },
  { scene: 'dark_wing',                  zh: '暗黑翅膀',          en: 'Dark Wing',                  units: 2,   category: 'wings' },

  // === 角色 ===
  { scene: 'venomous_spider',            zh: '毒液蜘蛛',          en: 'Venomous Spider',            units: 1.5, category: 'character' },
  { scene: 'throne_of_king',             zh: '王座',              en: 'Throne of King',             units: 3.5, category: 'character' },
  { scene: 'luminous_elf',               zh: '發光精靈',          en: 'Luminous Elf',               units: 3.5, category: 'character' },
  { scene: 'woodland_elf',               zh: '森林精靈',          en: 'Woodland Elf',               units: 3.5, category: 'character' },

  // === 動漫風格 ===
  { scene: 'japanese_anime_1',           zh: '日本動漫 1',        en: 'Japanese Anime 1',           units: 1.7, category: 'transform' },
  { scene: 'american_comics',            zh: '美式漫畫',          en: 'American Comics',            units: 1.7, category: 'transform' },

  // === 萬聖節 ===
  { scene: 'guardian_spirit',            zh: '守護靈',            en: 'Guardian Spirit',            units: 2,   category: 'halloween' },
  { scene: 'swish_swish',                zh: '咻咻',              en: 'Swish Swish',                units: 2.5, category: 'effect' },
  { scene: 'witch_transform',            zh: '巫師變身',          en: 'Witch Transform',            units: 3,   category: 'halloween' },
  { scene: 'vampire_transform',          zh: '吸血鬼變身',        en: 'Vampire Transform',          units: 3,   category: 'halloween' },
  { scene: 'pumpkin_head_transform',     zh: '南瓜頭變身',        en: 'Pumpkin Head Transform',     units: 3,   category: 'halloween' },
  { scene: 'demon_transform',            zh: '惡魔變身',          en: 'Demon Transform',            units: 3,   category: 'halloween' },
  { scene: 'mummy_transform',            zh: '木乃伊變身',        en: 'Mummy Transform',            units: 3,   category: 'halloween' },
  { scene: 'zombie_transform',           zh: '殭屍變身',          en: 'Zombie Transform',           units: 3,   category: 'halloween' },
  { scene: 'cute_pumpkin_transform',     zh: '可愛南瓜變身',      en: 'Cute Pumpkin Transform',     units: 4,   category: 'halloween' },
  { scene: 'cute_ghost_transform',       zh: '可愛幽靈變身',      en: 'Cute Ghost Transform',       units: 4,   category: 'halloween' },
  { scene: 'knock_knock_halloween',      zh: '萬聖叩門',          en: 'Knock Knock Halloween',      units: 4,   category: 'halloween' },
  { scene: 'halloween_escape',           zh: '萬聖節逃脫',        en: 'Halloween Escape',           units: 5,   category: 'halloween' },

  // === 通用特效 ===
  { scene: 'rampage_ape',                zh: '狂暴猩猩',          en: 'Rampage Ape',                units: 2,   category: 'character' },
  { scene: 'magic_fireball',             zh: '魔法火球',          en: 'Magic Fireball',             units: 1,   category: 'effect' },
  { scene: 'squeeze_scream',             zh: '擠壓尖叫',          en: 'Squeeze Scream',             units: 1.2, category: 'effect' },
  { scene: 'gallery_ring',               zh: '畫廊環繞',          en: 'Gallery Ring',               units: 2,   category: 'visual' },
  { scene: 'baseball',                   zh: '棒球',              en: 'Baseball',                   units: 3.5, category: 'action' },
  { scene: 'inner_voice',                zh: '內心獨白',          en: 'Inner Voice',                units: 2,   category: 'effect' },
  { scene: 'a_list_look',                zh: '巨星造型',          en: 'A List Look',                units: 1,   category: 'character' },
  { scene: 'memory_alive',               zh: '記憶重現',          en: 'Memory Alive',               units: 2,   category: 'effect' },
  { scene: 'trampoline',                 zh: '彈跳床',            en: 'Trampoline',                 units: 2,   category: 'action' },
  { scene: 'trampoline_night',           zh: '夜光彈跳床',        en: 'Trampoline Night',           units: 2,   category: 'action' },
  { scene: 'pucker_up',                  zh: '嘟嘴',              en: 'Pucker Up',                  units: 2,   category: 'character' },
  { scene: 'guess_what',                 zh: '猜猜看',            en: 'Guess What',                 units: 2,   category: 'effect' },
  { scene: 'feed_mooncake',              zh: '餵月餅',            en: 'Feed Mooncake',              units: 2,   category: 'effect' },
  { scene: 'flyer',                      zh: '飛行',              en: 'Flyer',                      units: 2,   category: 'action' },
  { scene: 'dishwasher',                 zh: '洗碗機',            en: 'Dishwasher',                 units: 1,   category: 'effect' },
  { scene: 'running_man',                zh: '奔跑男孩',          en: 'Running Man',                units: 2,   category: 'action' },
  { scene: 'disappear',                  zh: '消失',              en: 'Disappear',                  units: 2,   category: 'effect' },
  { scene: 'mythic_style',               zh: '神話風格',          en: 'Mythic Style',               units: 1.2, category: 'character' },
  { scene: 'steampunk',                  zh: '蒸汽龐克',          en: 'Steampunk',                  units: 2,   category: 'transform' },
  { scene: 'hug_from_past',              zh: '來自過去的擁抱',    en: 'Hug From Past',              units: 1,   category: 'romance' },
  { scene: 'firework',                   zh: '煙火',              en: 'Firework',                   units: 1,   category: 'visual' },
  { scene: 'media_interview',            zh: '媒體採訪',          en: 'Media Interview',            units: 1,   category: 'character' },
  { scene: 'heart_gesture_1',            zh: '比心',              en: 'Heart Gesture 1',            units: 1,   category: 'romance' },
  { scene: 'smoke_smoke',                zh: '煙霧瀰漫',          en: 'Smoke Smoke',                units: 1,   category: 'effect' },
  { scene: 'instant_kid',                zh: '瞬間變小孩',        en: 'Instant Kid',                units: 1,   category: 'transform' },
  { scene: 'dollar_rain',                zh: '美元雨',            en: 'Dollar Rain',                units: 1,   category: 'cny' },
  { scene: 'cry_cry',                    zh: '哭哭',              en: 'Cry Cry',                    units: 1,   category: 'effect' },
  { scene: 'building_collapse',          zh: '建築倒塌',          en: 'Building Collapse',          units: 1,   category: 'effect' },
  { scene: 'gun_shot',                   zh: '槍擊',              en: 'Gun Shot',                   units: 1,   category: 'action' },
  { scene: 'mushroom',                   zh: '蘑菇',              en: 'Mushroom',                   units: 1,   category: 'effect' },
  { scene: 'double_gun',                 zh: '雙槍',              en: 'Double Gun',                 units: 1,   category: 'action' },
  { scene: 'lightning_power',            zh: '閃電力量',          en: 'Lightning Power',            units: 1,   category: 'effect' },
  { scene: 'jesus_hug',                  zh: '耶穌擁抱',          en: 'Jesus Hug',                  units: 1,   category: 'character' },
  { scene: 'shark_alert',                zh: '鯊魚警報',          en: 'Shark Alert',                units: 1,   category: 'effect' },
  { scene: 'long_hair',                  zh: '長髮飄飄',          en: 'Long Hair',                  units: 1,   category: 'character' },
  { scene: 'lie_flat',                   zh: '躺平',              en: 'Lie Flat',                   units: 1,   category: 'effect' },
  { scene: 'polar_bear_hug',             zh: '北極熊抱抱',        en: 'Polar Bear Hug',             units: 1,   category: 'pet' },
  { scene: 'brown_bear_hug',             zh: '棕熊抱抱',          en: 'Brown Bear Hug',             units: 1,   category: 'pet' },
  { scene: 'jazz_jazz',                  zh: '爵士爵士',          en: 'Jazz Jazz',                  units: 1,   category: 'dance' },
  { scene: 'office_escape_plow',         zh: '辦公室逃脫',        en: 'Office Escape Plow',         units: 1,   category: 'action' },
  { scene: 'fly_fly',                    zh: '飛飛',              en: 'Fly Fly',                    units: 1,   category: 'action' },
  { scene: 'watermelon_bomb',            zh: '西瓜爆炸',          en: 'Watermelon Bomb',            units: 1,   category: 'effect' },
  { scene: 'boss_coming',                zh: '老闆來了',          en: 'Boss Coming',                units: 1,   category: 'effect' },
  { scene: 'wool_curly',                 zh: '羊毛捲',            en: 'Wool Curly',                 units: 1,   category: 'effect' },
  { scene: 'marry_me',                   zh: '嫁給我',            en: 'Marry Me',                   units: 1,   category: 'romance' },
  { scene: 'swing_swing',                zh: '盪鞦韆',            en: 'Swing Swing',                units: 2,   category: 'action' },
  { scene: 'day_to_night',               zh: '白天變夜晚',        en: 'Day To Night',               units: 2,   category: 'transition' },
  { scene: 'piggy_morph',                zh: '豬豬變身',          en: 'Piggy Morph',                units: 1,   category: 'transform' },
  { scene: 'wig_out',                    zh: '假髮起飛',          en: 'Wig Out',                    units: 1,   category: 'effect' },
  { scene: 'car_explosion',              zh: '車爆炸',            en: 'Car Explosion',              units: 1,   category: 'effect' },
  { scene: 'ski_ski',                    zh: '滑雪滑雪',          en: 'Ski Ski',                    units: 2,   category: 'action' },
  { scene: 'siblings',                   zh: '兄弟姐妹',          en: 'Siblings',                   units: 1,   category: 'character' },
  { scene: 'construction_worker',        zh: '工地工人',          en: 'Construction Worker',        units: 1,   category: 'character' },
  { scene: "let's_ride",                 zh: '出發吧',            en: "Let's Ride",                 units: 2,   category: 'action' },
  { scene: 'emoji',                      zh: '表情符號',          en: 'Emoji',                      units: 2,   category: 'effect' },
  { scene: 'snatched',                   zh: '搶走',              en: 'Snatched',                   units: 2,   category: 'action' },
  { scene: 'magic_broom',                zh: '魔法掃帚',          en: 'Magic Broom',                units: 2,   category: 'character' },
  { scene: 'felt_felt',                  zh: '羊毛氈質感',        en: 'Felt Felt',                  units: 2,   category: 'transform' },
  { scene: 'jumpdrop',                   zh: '跳下',              en: 'Jump Drop',                  units: 3.5, category: 'action' },
  { scene: 'surfsurf',                   zh: '衝浪',              en: 'Surf Surf',                  units: 2,   category: 'action' },
  { scene: 'skateskate',                 zh: '滑板',              en: 'Skate Skate',                units: 2,   category: 'action' },
  { scene: 'plushcut',                   zh: '絨毛切割',          en: 'Plush Cut',                  units: 2,   category: 'visual' },
  { scene: 'jelly_press',                zh: '果凍按壓',          en: 'Jelly Press',                units: 2,   category: 'visual' },
  { scene: 'jelly_slice',                zh: '果凍切片',          en: 'Jelly Slice',                units: 2,   category: 'visual' },
  { scene: 'jelly_squish',               zh: '果凍擠壓',          en: 'Jelly Squish',               units: 2,   category: 'visual' },
  { scene: 'jelly_jiggle',               zh: '果凍搖擺',          en: 'Jelly Jiggle',               units: 2,   category: 'visual' },
  { scene: 'pixelpixel',                 zh: '像素風格',          en: 'Pixel Pixel',                units: 2,   category: 'visual' },
  { scene: 'yearbook',                   zh: '畢業紀念冊',        en: 'Yearbook',                   units: 2,   category: 'character' },
  { scene: 'instant_film',               zh: '拍立得',            en: 'Instant Film',               units: 2,   category: 'visual' },
  { scene: 'anime_figure',               zh: '動漫公仔',          en: 'Anime Figure',               units: 2,   category: 'transform' },
  { scene: 'rocketrocket',               zh: '火箭升空',          en: 'Rocket Rocket',              units: 2,   category: 'action' },
  { scene: 'bloombloom',                 zh: '盛開盛開',          en: 'Bloom Bloom',                units: 3.5, category: 'visual' },
  { scene: 'dizzydizzy',                 zh: '頭暈目眩',          en: 'Dizzy Dizzy',                units: 3.5, category: 'effect' },
  { scene: 'fuzzyfuzzy',                 zh: '毛茸茸',            en: 'Fuzzy Fuzzy',                units: 2,   category: 'visual' },
  { scene: 'squish',                     zh: '擠壓',              en: 'Squish',                     units: 2,   category: 'visual' },
  { scene: 'expansion',                  zh: '膨脹',              en: 'Expansion',                  units: 2,   category: 'visual' },
]

export const KLING_USD_PER_UNIT = 0.14

export function getEffect(scene) {
  return KLING_EFFECTS.find(e => e.scene === scene) ?? null
}

export function effectsByCategory(catId) {
  if (catId === 'all') return KLING_EFFECTS
  return KLING_EFFECTS.filter(e => e.category === catId)
}

export function searchEffects(query) {
  if (!query) return KLING_EFFECTS
  const q = query.toLowerCase().trim()
  return KLING_EFFECTS.filter(e =>
    e.zh.toLowerCase().includes(q) ||
    e.en.toLowerCase().includes(q) ||
    e.scene.toLowerCase().includes(q)
  )
}
